name: flutter_calendar
description: A Flutter package with enhanced calendar UI featuring American date formatting, month names, and consistent week display.
version: 2.0.1
homepage: https://github.com/Mozahir1/flutter_calendar
issue_tracker: https://github.com/Mozahir1/flutter_calendar/issues

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints:
  flutter_test:
    sdk: flutter

flutter:
